on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          files=$(find packages -type d ! -exec test -d "{}/"* \; -print)
          json=$(printf '%s' "$files" | jq -R . | jq -s '{include: map({lib: .})}')

          {
            echo "matrix<<EOF"
            echo "$json"
            echo "EOF"
          } >> $GITHUB_OUTPUT
  

  install-library:
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Process file
        run: |
          echo "Processing ${{ matrix.lib }}"
          ls "${{ matrix.file }}"