name: Dynamic Matrix Example

on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}

    steps:
      - id: set
        run: |
          echo 'matrix={"include":[{"name":"job1","value":"A"},{"name":"job2","value":"B"}]}' >> $GITHUB_OUTPUT

  use-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Print values
        run: |
          echo "Name = ${{ matrix.name }}"
          echo "Value = ${{ matrix.value }}"